public enum StateEnum {
    Idle,
    IPSC_target,
    IPSC_noshot,
    USPSA_target,
    USPSA_noshot,
    Barrel,
    USPSAMiniPopper,
    USPSAPopper,
    Wall,
    Wall4,
    Remove,
    MoveStage,
    DrawShootingZone,
    StageRun,
    USPSA_rightDark,
    USPSA_leftDark,
    USPSA_leftRightDark
}
